[project]
name = "fastapi-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiomysql>=0.2.0",
    "fastapi>=0.115.12",
    "httptools>=0.6.4",
    "uvicorn>=0.34.0",
    "uvloop>=0.21.0",
]
